export { AppShell } from "./app-shell";
export { AppSidebar } from "./app-sidebar";
export { AppHeader } from "./app-header";
export { ConsoleNav, NavItem } from "./nav";
export { PageHeader } from "./page-header";
export { StatCard } from "./stat-card";
export { StatusBadge, ConnectionStatus } from "./status-badge";
export { TableToolbar, FilterSegmentedControl, TableFilterButton } from "./table-toolbar";
export { AppProvider, useApp } from "./app-context";
export type { ShellState, PendingAction, ActionErrors } from "./app-context";
export { deriveShellReadiness, deriveAuthSetupStep } from "./shell-readiness";
export type { ReadinessLevel, ShellReadinessSummary, AuthSetupStep } from "./shell-readiness";
export { ShellAuthPanel } from "./shell-auth-panel";
export { formatPresentedCommandFailure, presentCommandFailure } from "./command-failure-presenter";
export type { ClassifiedFailurePresentation, FailureSeverity } from "./command-failure-presenter";
